import { Nunito_Sans } from "next/font/google"
import "./globals.css"
import Header from "@/components/Header"

const nunito_sans = Nunito_Sans({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={nunito_sans.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
